# Model Comparison

This notebook compares the recommendations generated by two approaches:

- TF-IDF based recommender (Baseline): represents each musical work using extracted metadata features and measures similarity based on keyword overlap.
- Embedding-based recommender: represents each work using semantic embeddings generated from textual descriptions of musical features.

Several musical works are used as queries and the recommended results from both models are compared to evaluate similarities and differences.

In [1]:
from src.recommendation import recommend_embedding, recommend_tfidf, find_best_match

In [2]:
recommend_embedding(find_best_match('symphony 5 beethoven')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
10133,"Symphony no. 4 in C minor, D.417, ""Tragic""",Franz Schubert,Early Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
10135,"Symphony no. 8 in B minor, D.759, ""Unfinished""",Franz Schubert,Early Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
2461,Symphony in B minor,Claude Debussy,Late Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
2890,"Falstaff, symphonic study in C minor, op. 68",Edward Elgar,Late Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
5933,"Symphony no. 2 in C minor, ""Resurrection""",Gustav Mahler,Late Romantic,Symphony,Orchestral,Orchestra,Minor,NaN

In [3]:
recommend_tfidf(find_best_match('symphony 5 beethoven')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
10133,"Symphony no. 4 in C minor, D.417, ""Tragic""",Franz Schubert,Early Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
10135,"Symphony no. 8 in B minor, D.759, ""Unfinished""",Franz Schubert,Early Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
1580,Symphony no. 2 in B minor,Alexander Borodin,Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
1655,"Symphony no. 4 in E minor, op. 98",Johannes Brahms,Romantic,Symphony,Orchestral,Orchestra,Minor,NaN
1776,"Symphony no. 1 in C minor, op. 68",Johannes Brahms,Romantic,Symphony,Orchestral,Orchestra,Minor,NaN

In [4]:
recommend_embedding(find_best_match('piano concerto 2 rachmaninov')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
1015,"Piano Concerto no. 2 in G major, BB101, Sz.95",Béla Bartók,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
1016,"Piano Concerto no. 3 in E major, BB127, Sz.119",Béla Bartók,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
1911,"Piano Concerto in D major, op. 13",Benjamin Britten,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
6089,"Piano Concerto no. 1 in D major, H.149",Bohuslav Martinů,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
8150,"Piano Concerto no. 3 in C major, op. 26",Sergei Prokofiev,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN

In [5]:
recommend_tfidf(find_best_match('piano concerto 2 rachmaninov')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
1015,"Piano Concerto no. 2 in G major, BB101, Sz.95",Béla Bartók,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
1016,"Piano Concerto no. 3 in E major, BB127, Sz.119",Béla Bartók,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
1911,"Piano Concerto in D major, op. 13",Benjamin Britten,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
6089,"Piano Concerto no. 1 in D major, H.149",Bohuslav Martinů,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN
8150,"Piano Concerto no. 3 in C major, op. 26",Sergei Prokofiev,20th Century,Concerto,Orchestral,"Piano, Orchestra",Major,NaN

In [6]:
recommend_embedding(find_best_match('Tempo di valse in A major, JS 2')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
11730,"Valse à Betsy Lerche in A flat major, JS 1",Jean Sibelius,Late Romantic,Waltz,Keyboard,Piano,Major,NaN
11737,Waltz in D flat major,Jean Sibelius,Late Romantic,Waltz,Keyboard,Piano,Major,NaN
2148,"Waltz in A flat major, B.21",Frédéric Chopin,Romantic,Waltz,Keyboard,Piano,Major,NaN
2149,"Waltz in A flat major, op. 42",Frédéric Chopin,Romantic,Waltz,Keyboard,Piano,Major,NaN
2152,"Waltz in E flat major, B.46",Frédéric Chopin,Romantic,Waltz,Keyboard,Piano,Major,NaN

In [7]:
recommend_tfidf(find_best_match('Tempo di valse in A major, JS 2')['index'])

,title,composer_name,epoch,form,extended_genre,instrumentation,mode,tempo_marking
11730,"Valse à Betsy Lerche in A flat major, JS 1",Jean Sibelius,Late Romantic,Waltz,Keyboard,Piano,Major,NaN
11737,Waltz in D flat major,Jean Sibelius,Late Romantic,Waltz,Keyboard,Piano,Major,NaN
2467,"Valse romantique, L.71",Claude Debussy,Late Romantic,Waltz,Keyboard,Piano,NaN,NaN
8809,8 Valses nobles et sentimentales,Maurice Ravel,Late Romantic,Waltz,Keyboard,Piano,NaN,NaN
11728,"Valse lyrique, op. 96a",Jean Sibelius,Late Romantic,Waltz,Keyboard,Piano,NaN,NaN

## Model Comparison Conclusion

Because the embedding model was built from the same structured metadata used by the TF-IDF baseline, both approaches produced very similar recommendations.
This suggests that the quality of the representation is limited by the available metadata rather than the similarity algorithm itself.